/**
 * Plan d'Action 2026 - Données Initiales
 * Toutes les valeurs sont initialisées à ZÉRO
 * Version GitHub Ready
 */

const APP_DATA = {
    // Configuration application
    config: {
        version: "1.0.0",
        name: "Plan d'Action 2026",
        motto: "Réalisation et Constance",
        currency: "XAF",
        language: "fr",
        defaultTheme: "light",
        initialized: true,
        dateCreation: "2026-01-01T00:00:00Z"
    },

    // Utilisateurs
    users: {
        fabien: {
            id: "user_fabien",
            nom: "Fabien",
            username: "fabien",
            password: "fabien",
            role: "admin",
            vision: "Constance et Réalisation",
            theme: "Constance - Réalisation",
            avatar: "👨‍💼",
            nombreObjectifs: 6,
            scoreGlobal: 0,
            serieActuelle: 0,
            dateCreation: "2026-01-01T00:00:00Z",
            derniereConnexion: null,
            preferences: {
                theme: "light",
                notifications: true,
                sons: true
            }
        },
        sandrine: {
            id: "user_sandrine",
            nom: "Sandrine",
            username: "sandrine",
            password: "sandrine",
            role: "standard",
            vision: "Réalisation et Discipline",
            theme: "Réalisation - Discipline",
            avatar: "👩‍💼",
            nombreObjectifs: 10,
            scoreGlobal: 0,
            serieActuelle: 0,
            dateCreation: "2026-01-01T00:00:00Z",
            derniereConnexion: null,
            preferences: {
                theme: "light",
                notifications: true,
                sons: true
            }
        }
    },

    // Objectifs Fabien (6)
    objectifs: {
        // === FABIEN ===
        obj_fabien_bible: {
            id: "obj_fabien_bible",
            userId: "user_fabien",
            titre: "Lecture Bible - Ancien Testament (NIV)",
            description: "Lire l'Ancien Testament complet en version NIV anglais pour améliorer aussi l'anglais",
            domaine: "spirituel",
            categorie: "lecture_biblique",
            icon: "📖",
            frequence: "5x/semaine",
            joursActifs: ["lundi", "mardi", "mercredi", "jeudi", "vendredi"],
            cible: { type: "chapitres", valeur: 929, unite: "chapitres" },
            progression: { valeur: 0, pourcentage: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2027-03-31",
            statut: "active",
            evaluations: ["mois", "trimestre", "semestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_fabien_detox: {
            id: "obj_fabien_detox",
            userId: "user_fabien",
            titre: "Détox Fruits et Légumes",
            description: "Journées de détox uniquement fruits et légumes pour purifier le corps",
            domaine: "physique",
            categorie: "nutrition",
            icon: "🥗",
            frequence: "2x/mois (objectif 1x/semaine)",
            joursActifs: [],
            cible: { type: "sessions", valeur: 52, unite: "sessions/an" },
            progression: { valeur: 0, pourcentage: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            ficheSante: { energie: 0, digestion: 0, poids: 0, sommeil: 0, peau: 0, humeur: 0 },
            evaluations: ["session"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_fabien_anglais: {
            id: "obj_fabien_anglais",
            userId: "user_fabien",
            titre: "Apprentissage Anglais",
            description: "Passer de débutant à intermédiaire avec Duolingo et Praktika",
            domaine: "intellectuel",
            categorie: "langue_etrangere",
            icon: "🇬🇧",
            frequence: "5x/semaine, 5-15 min/jour",
            joursActifs: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            cible: { type: "niveau", valeur: "B1", niveauActuel: "A1" },
            progression: { valeur: 0, pourcentage: 0, xpTotal: 0 },
            serie: 0,
            applications: ["Duolingo", "Praktika"],
            competences: ["Lecture", "Communication", "Présentations"],
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["mois", "trimestre", "semestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_fabien_chinois: {
            id: "obj_fabien_chinois",
            userId: "user_fabien",
            titre: "Apprentissage Chinois Mandarin",
            description: "Progresser de HSK1 vers HSK2 avec HelloChinese",
            domaine: "intellectuel",
            categorie: "langue_etrangere",
            icon: "🇨🇳",
            frequence: "5x/semaine Lun-Ven, 15 min/jour",
            joursActifs: ["lundi", "mardi", "mercredi", "jeudi", "vendredi"],
            cible: { type: "niveau", valeur: "HSK2", niveauActuel: "HSK1", motsActuels: 150, motsCible: 300 },
            progression: { valeur: 0, pourcentage: 0, vocabulaire: 0, caracteres: 0 },
            serie: 0,
            applications: ["HelloChinese", "Pleco"],
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["mois", "trimestre", "semestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_fabien_epargne: {
            id: "obj_fabien_epargne",
            userId: "user_fabien",
            titre: "Épargne Annuelle",
            description: "Épargner 2 000 000 XAF sur l'année (150-200K/mois)",
            domaine: "financier",
            categorie: "epargne",
            icon: "💰",
            frequence: "Mensuel",
            joursActifs: [1],
            cible: { type: "montant", valeur: 2000000, unite: "XAF", mensuel: { min: 150000, max: 200000 } },
            progression: { valeur: 0, pourcentage: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["mois"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_fabien_aquacam: {
            id: "obj_fabien_aquacam",
            userId: "user_fabien",
            titre: "Projet Aquacam (Natation)",
            description: "Développer la visibilité et le CA au Cameroun et en Chine",
            domaine: "projet",
            categorie: "business",
            icon: "🏊",
            frequence: "Continu",
            joursActifs: [],
            cible: { type: "indicateurs", indicateurs: ["contacts", "caMensuel", "actionsMarketing", "presenceWeb"] },
            progression: { valeur: 0, pourcentage: 0, contacts: 0, caMensuel: 0, actionsMarketing: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["mois"],
            dateCreation: "2026-01-01T00:00:00Z"
        },

        // === SANDRINE ===
        obj_sandrine_priere: {
            id: "obj_sandrine_priere",
            userId: "user_sandrine",
            titre: "Prière quotidienne",
            description: "Temps de prière minimum 1h par jour",
            domaine: "spirituel",
            categorie: "priere",
            icon: "🙏",
            frequence: "Quotidien",
            joursActifs: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            cible: { type: "duree", valeur: 60, unite: "minutes/jour" },
            progression: { valeur: 0, pourcentage: 0, totalMinutes: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["trimestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_bible: {
            id: "obj_sandrine_bible",
            userId: "user_sandrine",
            titre: "Lecture Bible + Étude approfondie",
            description: "2 chapitres/jour + étude approfondie d'un livre biblique",
            domaine: "spirituel",
            categorie: "lecture_biblique",
            icon: "📖",
            frequence: "Quotidien",
            joursActifs: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            cible: { type: "chapitres", valeur: 2, unite: "chapitres/jour" },
            progression: { valeur: 0, pourcentage: 0, totalChapitres: 0 },
            serie: 0,
            livreEtude: null,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["trimestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_piano: {
            id: "obj_sandrine_piano",
            userId: "user_sandrine",
            titre: "Apprentissage Piano",
            description: "Sessions de piano 2 fois par semaine",
            domaine: "intellectuel",
            categorie: "musique",
            icon: "🎹",
            frequence: "2x/semaine",
            joursActifs: ["mardi", "jeudi"],
            cible: { type: "sessions", valeur: 2, unite: "sessions/semaine" },
            progression: { valeur: 0, pourcentage: 0, totalSessions: 0 },
            serie: 0,
            echeance: "2026-02-28",
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["trimestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_francais: {
            id: "obj_sandrine_francais",
            userId: "user_sandrine",
            titre: "Révision Français",
            description: "Grammaire, orthographe et conjugaison chaque dimanche (perte de réflexes, besoin professionnel)",
            domaine: "intellectuel",
            categorie: "langue_maternelle",
            icon: "📚",
            frequence: "1x/semaine (dimanche)",
            joursActifs: ["dimanche"],
            cible: { type: "sessions", valeur: 1, unite: "session/semaine" },
            progression: { valeur: 0, pourcentage: 0, totalSessions: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["trimestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_anglais: {
            id: "obj_sandrine_anglais",
            userId: "user_sandrine",
            titre: "Apprentissage Anglais",
            description: "Duolingo 15min/jour + app payante mars 2026 pour expression orale + 2 chansons à traduire",
            domaine: "intellectuel",
            categorie: "langue_etrangere",
            icon: "🇬🇧",
            frequence: "Quotidien, 15 min/jour",
            joursActifs: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            cible: { type: "duree", valeur: 15, unite: "minutes/jour", chansons: 2 },
            progression: { valeur: 0, pourcentage: 0, xpTotal: 0, chansonsTraduites: 0 },
            serie: 0,
            applications: ["Duolingo"],
            appPayanteMars: true,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["trimestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_lecture: {
            id: "obj_sandrine_lecture",
            userId: "user_sandrine",
            titre: "Lecture de livres",
            description: "2 livres: 'Conseil à l'économe' Ellen White (2-3 ch/sem) + 1 autre à choisir",
            domaine: "intellectuel",
            categorie: "lecture",
            icon: "📚",
            frequence: "2-3 chapitres/semaine",
            joursActifs: [],
            cible: { type: "livres", valeur: 2, livres: [
                { titre: "Conseil à l'économe", auteur: "Ellen G. White", chapitresLus: 0 },
                { titre: "À choisir", auteur: "", chapitresLus: 0 }
            ]},
            progression: { valeur: 0, pourcentage: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["trimestre"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_epargne: {
            id: "obj_sandrine_epargne",
            userId: "user_sandrine",
            titre: "Épargne Mensuelle",
            description: "200K XAF/mois pour: soutenir maman, épargne investissements, soutien famille, studio septembre 2026",
            domaine: "financier",
            categorie: "epargne",
            icon: "💰",
            frequence: "Mensuel",
            joursActifs: [1],
            cible: { type: "montant", valeur: 200000, unite: "XAF/mois" },
            progression: { valeur: 0, pourcentage: 0 },
            serie: 0,
            destinations: [
                { nom: "Soutenir maman (dettes)", montant: 0 },
                { nom: "Épargne investissements", montant: 0 },
                { nom: "Soutien frères/sœurs", montant: 0 },
                { nom: "Studio moderne sept 2026", montant: 0, plafond: 50000 }
            ],
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["mois"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_sport: {
            id: "obj_sandrine_sport",
            userId: "user_sandrine",
            titre: "Sport hebdomadaire",
            description: "2 séances par semaine (samedi et dimanche), maintenir 70kg",
            domaine: "physique",
            categorie: "sport",
            icon: "🏃",
            frequence: "2x/semaine",
            joursActifs: ["samedi", "dimanche"],
            cible: { type: "sessions", valeur: 2, unite: "sessions/semaine", poidsCible: 70 },
            progression: { valeur: 0, pourcentage: 0, totalSessions: 0, poidsActuel: null },
            serie: 0,
            dateDebut: "2026-01-06",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["mois"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_fruits: {
            id: "obj_sandrine_fruits",
            userId: "user_sandrine",
            titre: "Petit-déjeuner fruits",
            description: "Fruits au petit-déjeuner 2 fois par semaine (lundi et jeudi)",
            domaine: "physique",
            categorie: "nutrition",
            icon: "🍎",
            frequence: "2x/semaine",
            joursActifs: ["lundi", "jeudi"],
            cible: { type: "sessions", valeur: 2, unite: "fois/semaine" },
            progression: { valeur: 0, pourcentage: 0, totalFois: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["mois"],
            dateCreation: "2026-01-01T00:00:00Z"
        },
        obj_sandrine_ponctualite: {
            id: "obj_sandrine_ponctualite",
            userId: "user_sandrine",
            titre: "Ponctualité au travail",
            description: "Arriver 15-30 min en avance, départ maison max 06h45",
            domaine: "physique",
            categorie: "discipline",
            icon: "⏰",
            frequence: "Lun-Ven",
            joursActifs: ["lundi", "mardi", "mercredi", "jeudi", "vendredi"],
            cible: { type: "heure", heureDepartMax: "06:45", avanceMinutes: { min: 15, max: 30 } },
            progression: { valeur: 0, pourcentage: 0, joursALHeure: 0 },
            serie: 0,
            dateDebut: "2026-01-01",
            dateFin: "2026-12-31",
            statut: "active",
            evaluations: ["mois"],
            dateCreation: "2026-01-01T00:00:00Z"
        }
    },

    // Alarmes pré-configurées
    alarmes: {
        // === FABIEN ===
        alarme_fabien_bible: {
            id: "alarme_fabien_bible",
            userId: "user_fabien",
            objectifId: "obj_fabien_bible",
            titre: "📖 Lecture Bible",
            message: "Temps de lecture de la Bible !",
            heure: "06:30",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi"],
            recurrence: "hebdomadaire",
            son: "defaut",
            actif: true,
            snooze: 5
        },
        alarme_fabien_detox: {
            id: "alarme_fabien_detox",
            userId: "user_fabien",
            objectifId: "obj_fabien_detox",
            titre: "🥗 Préparation Détox",
            message: "Prépare ta détox de demain !",
            heure: "20:00",
            jours: [],
            recurrence: "veille_detox",
            son: "defaut",
            actif: true,
            snooze: 10
        },
        alarme_fabien_anglais: {
            id: "alarme_fabien_anglais",
            userId: "user_fabien",
            objectifId: "obj_fabien_anglais",
            titre: "🇬🇧 Anglais",
            message: "Duolingo t'attend !",
            heure: "19:00",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            recurrence: "quotidien",
            son: "defaut",
            actif: true,
            snooze: 5
        },
        alarme_fabien_chinois: {
            id: "alarme_fabien_chinois",
            userId: "user_fabien",
            objectifId: "obj_fabien_chinois",
            titre: "🇨🇳 Chinois",
            message: "Pause chinois !",
            heure: "12:30",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi"],
            recurrence: "hebdomadaire",
            son: "defaut",
            actif: true,
            snooze: 5
        },
        alarme_fabien_epargne: {
            id: "alarme_fabien_epargne",
            userId: "user_fabien",
            objectifId: "obj_fabien_epargne",
            titre: "💰 Épargne",
            message: "Pense à faire ton épargne mensuelle !",
            heure: "09:00",
            jours: [1],
            recurrence: "mensuel",
            son: "defaut",
            actif: true,
            snooze: 30
        },
        alarme_fabien_saisie: {
            id: "alarme_fabien_saisie",
            userId: "user_fabien",
            objectifId: null,
            titre: "📝 Saisie quotidienne",
            message: "N'oublie pas de saisir ta journée !",
            heure: "21:00",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            recurrence: "quotidien",
            son: "defaut",
            actif: true,
            snooze: 15
        },

        // === SANDRINE ===
        alarme_sandrine_priere: {
            id: "alarme_sandrine_priere",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_priere",
            titre: "🙏 Prière",
            message: "Temps de prière !",
            heure: "05:30",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            recurrence: "quotidien",
            son: "defaut",
            actif: true,
            snooze: 5
        },
        alarme_sandrine_bible: {
            id: "alarme_sandrine_bible",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_bible",
            titre: "📖 Lecture Bible",
            message: "Lecture biblique !",
            heure: "06:00",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            recurrence: "quotidien",
            son: "defaut",
            actif: true,
            snooze: 5
        },
        alarme_sandrine_piano: {
            id: "alarme_sandrine_piano",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_piano",
            titre: "🎹 Piano",
            message: "Session piano !",
            heure: "18:00",
            jours: ["mardi", "jeudi"],
            recurrence: "hebdomadaire",
            son: "defaut",
            actif: true,
            snooze: 10
        },
        alarme_sandrine_francais: {
            id: "alarme_sandrine_francais",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_francais",
            titre: "📚 Français",
            message: "Révision français !",
            heure: "15:00",
            jours: ["dimanche"],
            recurrence: "hebdomadaire",
            son: "defaut",
            actif: true,
            snooze: 10
        },
        alarme_sandrine_anglais: {
            id: "alarme_sandrine_anglais",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_anglais",
            titre: "🇬🇧 Anglais",
            message: "Duolingo !",
            heure: "12:00",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            recurrence: "quotidien",
            son: "defaut",
            actif: true,
            snooze: 5
        },
        alarme_sandrine_lecture: {
            id: "alarme_sandrine_lecture",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_lecture",
            titre: "📚 Lecture",
            message: "Temps de lecture !",
            heure: "21:30",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            recurrence: "quotidien",
            son: "defaut",
            actif: true,
            snooze: 10
        },
        alarme_sandrine_epargne: {
            id: "alarme_sandrine_epargne",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_epargne",
            titre: "💰 Épargne",
            message: "Épargne mensuelle !",
            heure: "08:00",
            jours: [1],
            recurrence: "mensuel",
            son: "defaut",
            actif: true,
            snooze: 30
        },
        alarme_sandrine_sport: {
            id: "alarme_sandrine_sport",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_sport",
            titre: "🏃 Sport",
            message: "C'est l'heure du sport !",
            heure: "07:00",
            jours: ["samedi", "dimanche"],
            recurrence: "hebdomadaire",
            son: "defaut",
            actif: true,
            snooze: 10
        },
        alarme_sandrine_fruits: {
            id: "alarme_sandrine_fruits",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_fruits",
            titre: "🍎 Fruits",
            message: "Petit-déjeuner fruits !",
            heure: "06:15",
            jours: ["lundi", "jeudi"],
            recurrence: "hebdomadaire",
            son: "defaut",
            actif: true,
            snooze: 5
        },
        alarme_sandrine_ponctualite: {
            id: "alarme_sandrine_ponctualite",
            userId: "user_sandrine",
            objectifId: "obj_sandrine_ponctualite",
            titre: "⏰ Ponctualité",
            message: "Prépare-toi pour le travail !",
            heure: "06:30",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi"],
            recurrence: "hebdomadaire",
            son: "defaut",
            actif: true,
            snooze: 5
        },
        alarme_sandrine_saisie: {
            id: "alarme_sandrine_saisie",
            userId: "user_sandrine",
            objectifId: null,
            titre: "📝 Saisie quotidienne",
            message: "N'oublie pas de saisir ta journée !",
            heure: "21:00",
            jours: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
            recurrence: "quotidien",
            son: "defaut",
            actif: true,
            snooze: 15
        }
    },

    // Entrées quotidiennes (vide au départ)
    entries: {},

    // Évaluations (vide au départ)
    evaluations: {},

    // Constantes domaines
    domaines: {
        spirituel: { nom: "Spirituel", icon: "🙏", color: "#9b59b6" },
        intellectuel: { nom: "Intellectuel", icon: "🧠", color: "#3498db" },
        financier: { nom: "Financier", icon: "💰", color: "#27ae60" },
        physique: { nom: "Physique", icon: "💪", color: "#e74c3c" },
        projet: { nom: "Projet", icon: "💼", color: "#f39c12" }
    },

    // Jours de la semaine
    jours: ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
    joursAbrev: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
    mois: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"]
};

// Export pour utilisation
if (typeof module !== 'undefined' && module.exports) {
    module.exports = APP_DATA;
}
